"""
DOCX Skill for Hermes Agent
Professional Word document creation and processing.
"""

import os
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.style import WD_STYLE_TYPE
from docx.oxml.ns import qn
from docx.oxml import OxmlElement
import subprocess


def create_professional_docx(title: str, sections: list, output_path: str,
                              author: str = "Hermes Agent") -> str:
    """Create a professional Word document.
    
    sections format: [
        {"heading": "Section Title", "content": "Paragraph text..."},
        {"heading": "Next Section", "content": "More text...", "bullets": ["item1", "item2"]}
    ]
    """
    doc = Document()
    
    # Set narrow margins
    for section in doc.sections:
        section.top_margin = Inches(0.7)
        section.bottom_margin = Inches(0.7)
        section.left_margin = Inches(0.8)
        section.right_margin = Inches(0.8)
    
    # Title
    title_para = doc.add_paragraph()
    title_run = title_para.add_run(title)
    title_run.bold = True
    title_run.font.size = Pt(18)
    title_run.font.color.rgb = RGBColor(26, 54, 93)
    title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    # Add author/date
    meta = doc.add_paragraph()
    meta_run = meta.add_run(f"Generated by {author}")
    meta_run.font.size = Pt(9)
    meta_run.font.color.rgb = RGBColor(100, 100, 100)
    meta.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    doc.add_paragraph()  # Spacer
    
    for section_data in sections:
        # Heading
        if section_data.get("heading"):
            heading = doc.add_heading(section_data["heading"], level=1)
        
        # Content
        if section_data.get("content"):
            para = doc.add_paragraph(section_data["content"])
            para.paragraph_format.space_after = Pt(8)
        
        # Bullets
        if section_data.get("bullets"):
            for bullet in section_data["bullets"]:
                p = doc.add_paragraph(bullet, style='List Bullet')
        
        # Optional page break
        if section_data.get("page_break"):
            doc.add_page_break()
    
    doc.save(output_path)
    return output_path


def read_docx_to_markdown(docx_path: str) -> str:
    """Read a .docx file and return clean markdown."""
    doc = Document(docx_path)
    lines = []
    
    for para in doc.paragraphs:
        style = para.style.name if para.style else "Normal"
        text = para.text.strip()
        if not text:
            continue
        
        if "Heading 1" in style:
            lines.append(f"# {text}")
        elif "Heading 2" in style:
            lines.append(f"## {text}")
        elif "Heading 3" in style:
            lines.append(f"### {text}")
        else:
            lines.append(text)
    
    # Add tables as markdown
    for table in doc.tables:
        lines.append("\n| " + " | ".join([cell.text.strip() for cell in table.rows[0].cells]) + " |")
        lines.append("|" + "---|" * len(table.rows[0].cells))
        for row in table.rows[1:]:
            lines.append("| " + " | ".join([cell.text.strip() for cell in row.cells]) + " |")
        lines.append("")
    
    return "\n".join(lines)


def fill_docx_template(template_path: str, replacements: dict, output_path: str) -> str:
    """Simple template filling by replacing {{KEY}} placeholders."""
    doc = Document(template_path)
    
    for para in doc.paragraphs:
        for key, value in replacements.items():
            placeholder = f"{{{{{key}}}}}"
            if placeholder in para.text:
                for run in para.runs:
                    if placeholder in run.text:
                        run.text = run.text.replace(placeholder, str(value))
    
    doc.save(output_path)
    return output_path


def docx_to_pdf(docx_path: str, output_pdf: str) -> str:
    """Convert .docx to PDF using LibreOffice (must be installed)."""
    cmd = [
        "libreoffice", "--headless", "--convert-to", "pdf",
        "--outdir", os.path.dirname(output_pdf) or ".",
        docx_path
    ]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(f"LibreOffice conversion failed: {result.stderr}")
    
    # LibreOffice creates PDF with same base name
    base = os.path.splitext(os.path.basename(docx_path))[0]
    generated_pdf = os.path.join(os.path.dirname(output_pdf) or ".", f"{base}.pdf")
    if os.path.exists(generated_pdf) and generated_pdf != output_pdf:
        os.rename(generated_pdf, output_pdf)
    return output_pdf
